# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort
      language: python
      language_version: 3.10.12
      types: [ python ]
    - id: black
      name: black
      entry: black
      language: python
      language_version: 3.10.12
      types: [ python ]
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      language_version: 3.10.12
      types: [ python ]
      additional_dependencies: [flake8-docstrings]
      args: [ --config=.flake8]
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      language_version: 3.10.12
      types: [ python ]
      args: [ --config-file=pyproject.toml]
